set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]
set_property PACKAGE_PIN J18 [get_ports {vga_blue[3]}]
set_property PACKAGE_PIN K18 [get_ports {vga_blue[2]}]
set_property PACKAGE_PIN L18 [get_ports {vga_blue[1]}]
set_property PACKAGE_PIN N18 [get_ports {vga_blue[0]}]
set_property PACKAGE_PIN D17 [get_ports {vga_green[3]}]
set_property PACKAGE_PIN G17 [get_ports {vga_green[2]}]
set_property PACKAGE_PIN H17 [get_ports {vga_green[1]}]
set_property PACKAGE_PIN J17 [get_ports {vga_green[0]}]
set_property PACKAGE_PIN N19 [get_ports {vga_red[3]}]
set_property PACKAGE_PIN J19 [get_ports {vga_red[2]}]
set_property PACKAGE_PIN H19 [get_ports {vga_red[1]}]
set_property PACKAGE_PIN G19 [get_ports {vga_red[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN P19 [get_ports h_sync]
set_property PACKAGE_PIN R2 [get_ports rst]
set_property PACKAGE_PIN R19 [get_ports v_sync]

set_property IOSTANDARD LVCMOS33 [get_ports {move_sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {move_sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {move_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {move_sw[0]}]
set_property PACKAGE_PIN W17 [get_ports {move_sw[3]}]
set_property PACKAGE_PIN W16 [get_ports {move_sw[2]}]
set_property PACKAGE_PIN V16 [get_ports {move_sw[1]}]
set_property PACKAGE_PIN V17 [get_ports {move_sw[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports cd_led]
set_property PACKAGE_PIN U16 [get_ports cd_led]

set_property IOSTANDARD LVCMOS33 [get_ports pb_c]
set_property PACKAGE_PIN U18 [get_ports pb_c]

set_property IOSTANDARD LVCMOS33 [get_ports {act_cd_state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {act_cd_state[0]}]
set_property PACKAGE_PIN W18 [get_ports {act_cd_state[1]}]
set_property PACKAGE_PIN V19 [get_ports {act_cd_state[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]
set_property PACKAGE_PIN C17 [get_ports ps2_clk]
set_property PACKAGE_PIN B17 [get_ports ps2_data]

set_property IOSTANDARD LVCMOS33 [get_ports {D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {now_state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {now_state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_out[0]}]
set_property PACKAGE_PIN W7 [get_ports {D[7]}]
set_property PACKAGE_PIN W6 [get_ports {D[6]}]
set_property PACKAGE_PIN U8 [get_ports {D[5]}]
set_property PACKAGE_PIN V8 [get_ports {D[4]}]
set_property PACKAGE_PIN U5 [get_ports {D[3]}]
set_property PACKAGE_PIN V5 [get_ports {D[2]}]
set_property PACKAGE_PIN U7 [get_ports {D[1]}]
set_property PACKAGE_PIN V7 [get_ports {D[0]}]
set_property PACKAGE_PIN L1 [get_ports {now_state[1]}]
set_property PACKAGE_PIN P1 [get_ports {now_state[0]}]
set_property PACKAGE_PIN W4 [get_ports {ssd_out[3]}]
set_property PACKAGE_PIN V4 [get_ports {ssd_out[2]}]
set_property PACKAGE_PIN U4 [get_ports {ssd_out[1]}]
set_property PACKAGE_PIN U2 [get_ports {ssd_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports pause]
set_property PACKAGE_PIN V17 [get_ports pause]
set_property IOSTANDARD LVCMOS33 [get_ports stop_state]
set_property PACKAGE_PIN P3 [get_ports stop_state]


set_property IOSTANDARD LVCMOS33 [get_ports LRCK]
set_property IOSTANDARD LVCMOS33 [get_ports MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SCK]
set_property IOSTANDARD LVCMOS33 [get_ports Stdin]
set_property PACKAGE_PIN A14 [get_ports MCLK]
set_property PACKAGE_PIN A16 [get_ports LRCK]
set_property PACKAGE_PIN B15 [get_ports SCK]
set_property PACKAGE_PIN B16 [get_ports Stdin]

set_property IOSTANDARD LVCMOS33 [get_ports sw_t1]
set_property PACKAGE_PIN T1 [get_ports sw_t1]

set_property IOSTANDARD LVCMOS33 [get_ports otk_led]
set_property PACKAGE_PIN V13 [get_ports otk_led]
